# промышленный протокинетический резак
- type: entity
  parent: BaseItem
  id: WeaponProtoKineticCutterIndustrial
  name: промышленный протокинетический резак
  suffix: LavaLand
  description: Стреляет кинетическими зарядами с низким уроном на короткое расстояние.
  components:
  - type: Sprite
    sprite: Adventure/Roles/LavaLand/Equipment/industrial_kinetic_cutter.rsi
    layers:
    - state: icon
      map: ["enum.GunVisualLayers.Base"]
  - type: Clothing
    slots:
    - suitStorage
    sprite: Adventure/Roles/LavaLand/Equipment/industrial_kinetic_cutter.rsi
  - type: Item
    size: Large
    sprite: Adventure/Roles/LavaLand/Equipment/industrial_kinetic_cutter.rsi
  - type: Gun
    selectedMode: SemiAuto
    availableModes:
    - SemiAuto
    fireRate: 0.5
    maxAngle: 50
    minAngle: 40
    soundGunshot:
      path: /Audio/Adventure/LavaLand/cutter_shot.ogg
      params:
        volume: 8
    soundEmpty:
      path: /Audio/Effects/box_deploy.ogg
  - type: GunRequiresWield
  - type: Wieldable
    unwieldOnUse: false
  - type: GunWieldBonus
    minAngle: -30
    maxAngle: -30
  - type: AmmoCounter
  - type: Appearance
  - type: ClothingSpeedModifier
    walkModifier: 0.90
    sprintModifier: 0.90
  - type: HeldSpeedModifier
  - type: UseDelay
    delay: 0.5
  - type: Battery
    maxCharge: 100
    startingCharge: 100
    pricePerJoule: 0.15
  - type: ProjectileBatteryAmmoProvider
    proto: BulletKinetic
    fireCost: 1
  - type: BatteryWeaponFireModes
    fireModes:
    - proto: BulletKinetic
      fireCost: 1
    - proto: BulletKineticCutterSpread
      fireCost: 5
    - proto: BulletKineticCutterSpreadSix
      fireCost: 10
  - type: BatterySelfRecharger
    autoRechargeRate: 2
    autoRecharge: true

- type: entity
  id: BulletKineticCutterSpreadSix
  name: раздробленный кинетический заряд
  categories: [ HideSpawnMenu ]
  parent: BulletKineticCutter
  components:
  - type: ProjectileSpread
    proto: BulletKineticCutter
    count: 6
    spread: 20