#Пожирание
- type: entity
  id: ActionDevourHungerSwarm
  name: "[color=red]Пожирать[/color]"
  description: Ешьте всё!
  categories: [ HideSpawnMenu ]
  components:
  - type: EntityTargetAction
    icon: { sprite : Interface/Actions/devour.rsi, state: icon }
    iconOn: { sprite : Interface/Actions/devour.rsi, state: icon-on }
    event: !type:DevourActionEvent
    priority: 1

# Построить слизь
- type: entity
  id: ActionHungerSwarmWeb
  name: Построить слизь
  description: Слизь - ваш друг и союзнить, распространяйте её чтобы замедлить ваших врагов, а нахождение на ней усиливает вашу регенерацию.
  categories: [ HideSpawnMenu ]
  components:
  - type: InstantAction
    icon:
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      state: tile
    event: !type:SpiderWebActionEvent
    useDelay: 20

#Строительство стены
- type: entity
  id: ActionHungerSwarmWall
  name: Построить стену улья
  description: Возведите стену для защиты улья.
  categories: [ HideSpawnMenu ]
  components:
  - type: WorldTargetAction
    useDelay: 20
    range: 1.5
    itemIconStyle: BigAction
    icon:
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      state: wall
    event: !type:WorldSpawnSpellEvent
      prototypes:
      - id: HungerSwarmWallSpawn
        amount: 1

#Строительство укреплённой стены
- type: entity
  id: ActionHungerSwarmWallReinforse
  name: Построить укреплённую стену улья
  description: Возведите стену для защиты улья.
  categories: [ HideSpawnMenu ]
  components:
  - type: WorldTargetAction
    useDelay: 30
    range: 1.5
    itemIconStyle: BigAction
    icon:
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      state: reinforce_wall
    event: !type:WorldSpawnSpellEvent
      prototypes:
      - id: HungerSwarmWallReinforceSpawn
        amount: 1

#Строительство двери
- type: entity
  id: ActionHungerSwarmDoor
  name: Построить проход улья
  description: Возведите проход для защиты улья.
  categories: [ HideSpawnMenu ]
  components:
  - type: WorldTargetAction
    useDelay: 40
    range: 1.5
    itemIconStyle: BigAction
    icon:
      sprite: Adventure/Roles/Hungry_Swarm/door.rsi
      state: closed
    event: !type:WorldSpawnSpellEvent
      prototypes:
      - id: HungerSwarmDoorSpawn
        amount: 1

#Построить биоэлюмистентную слизь
- type: entity
  id: ActionHungerSwarmWebLight
  name: Построить биоэлюмистентную слизь
  description: Возведите особый вид слизи, чтобы подсветить себе путь.
  categories: [ HideSpawnMenu ]
  components:
  - type: WorldTargetAction
    useDelay: 20
    range: 1.5
    itemIconStyle: BigAction
    icon:
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      state: light
    event: !type:WorldSpawnSpellEvent
      prototypes:
      - id: HungerSwarmWebLight
        amount: 1

#Построить липкую слизь
- type: entity
  id: ActionHungerSwarmWebSticky
  name: Построить липкую слизь
  description: Возведите особый вид слизи, чтобы замедлять врага ещё лучше.
  categories: [ HideSpawnMenu ]
  components:
  - type: WorldTargetAction
    useDelay: 20
    range: 1.5
    itemIconStyle: BigAction
    icon:
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      state: web
    event: !type:WorldSpawnSpellEvent
      prototypes:
      - id: HungerSwarmWebSticky
        amount: 1

#Отложить яйцо
- type: entity
  id: ActionHungerSwarmLayEgg
  name: Отложить яйцо
  description: Пришло время размножиться.
  categories: [ HideSpawnMenu ]
  components:
  - type: InstantAction
    icon:
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      state: egg
    useDelay: 60
    event: !type:EggLayInstantActionEvent

#постройка
- type: entity
  parent: BaseSubdermalImplant 
  id: ActionHungerSwarmWallImplant
  name: Построить стену улья
  categories: [ HideSpawnMenu ]
  components:
    - type: SubdermalImplant
      implantAction: ActionHungerSwarmWall 

- type: entity
  parent: BaseSubdermalImplant 
  id: ActionHungerSwarmWallReinforseImplant
  name: Построить укреплённую стену улья
  categories: [ HideSpawnMenu ]
  components:
    - type: SubdermalImplant
      implantAction: ActionHungerSwarmWallReinforse 

- type: entity
  parent: BaseSubdermalImplant 
  id: ActionHungerSwarmDoorImplant
  name: Построить проход улья
  categories: [ HideSpawnMenu ]
  components:
    - type: SubdermalImplant
      implantAction: ActionHungerSwarmDoor 

- type: entity
  parent: BaseSubdermalImplant 
  id: ActionHungerSwarmWebLightImplant
  name: Построить биоэлюмистентную слизь
  categories: [ HideSpawnMenu ]
  components:
    - type: SubdermalImplant
      implantAction: ActionHungerSwarmWebLight 

- type: entity
  parent: BaseSubdermalImplant 
  id: ActionHungerSwarmWebStickyImplant
  name: Построить липкую слизь
  categories: [ HideSpawnMenu ]
  components:
    - type: SubdermalImplant
      implantAction: ActionHungerSwarmWebSticky 

#Вырасти в жнеца
- type: entity
  id: ReaperEvolutionAction
  name: Вырасти в жнеца
  description: Пришло время стать взрослее.
  categories: [ HideSpawnMenu ]
  components:
  - type: InstantAction
    icon:
      sprite: Adventure/Roles/Hungry_Swarm/reaper.rsi
      state: icon
    event: !type:ReformEvent {}
    useDelay: 60

#Эволюционировать в стража
- type: entity
  id: ReaperQuardianEvolutionAction
  name: Эволюционировать в стража
  description: Став стражем, вы станите более мобильным, но не сможете строить улей.
  categories: [ HideSpawnMenu ]
  components:
  - type: InstantAction
    icon:
      sprite: Adventure/Roles/Hungry_Swarm/guardian.rsi
      state: icon
    event: !type:ReformEvent {}
    useDelay: 500

#Выпустить жало
- type: entity
  categories: [ HideSpawnMenu ]
  id: ActionReaperSting
  name: Выпустить жало
  description: Используйте своё жало чтобы убивать врагов (доступно раз в 5 секунд).
  components:
  - type: WorldTargetAction
    useDelay: 5
    itemIconStyle: BigAction
    icon:
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      state: sting
    event: !type:ActionGunShootEvent
    priority: 100
    checkCanAccess: false
    range: 0

#Избрать хранителя
- type: entity
  id: ActionForceKeeper
  name: Избрать хранителя
  categories: [ HideSpawnMenu ]
  description: Преобразите стражей улья в своих личных хранителей.
  components:
  - type: WorldTargetAction
    useDelay: 300
    itemIconStyle: BigAction
    checkCanAccess: false
    raiseOnUser: true
    range: 2
    sound: !type:SoundPathSpecifier
      path: /Audio/Adventure/Hungry_Swarm/insect_attack.ogg
    icon:
      sprite: Adventure/Roles/Hungry_Swarm/keeper.rsi
      state: icon
    event: !type:ProjectileSpellEvent
      prototype: ProjectilePolyboltHungerSwarmKeeper

- type: entity
  parent: BaseSubdermalImplant 
  id: ActionForceKeeperImplant
  name: Избрать хранителя
  categories: [ HideSpawnMenu ]
  components:
    - type: SubdermalImplant
      implantAction: ActionForceKeeper 