#База жуков
- type: entity
  abstract: true
  parent: [ SimpleSpaceMobBase, MobCombat ]
  id: BaseMobInsectSwarm
  components:
  - type: Sharp
  - type: NpcFactionMember
    factions:
    - Xeno
  - type: HTN
    rootTask:
      task: XenoCompound
    blackboard:
      NavClimb: !type:Bool
        true
      NavInteract: !type:Bool
        true
      NavPry: !type:Bool
        true
      NavSmash: !type:Bool
        true
  - type: Prying 
    pryPowered: true
    force: true
    speedModifier: 1.5
    useSound:
      path: /Audio/Items/crowbar.ogg
  - type: NoSlip
  - type: CombatMode
  - type: MobState
    allowedStates:
    - Alive
    - Dead
  - type: DamageStateVisuals
    states:
      Alive:
        Base: alive
      Dead:
        Base: dead
  - type: Inventory
    templateId: HungerSwarm
  - type: InventorySlots
  - type: Loadout
    prototypes: [HungerSwarm]
  - type: TriggerOnMobstateChange
    mobState:
    - Dead
  - type: EmitSoundOnTrigger
    sound:
      path: /Audio/Adventure/Hungry_Swarm/insect_dead.ogg
      params:
        volume: -2
  - type: Damageable
    damageModifierSet: HungerSwarm
  - type: Speech
    speechVerb: LargeMob
    speechSounds: HungerSwarmSpeech
  - type: EmitSoundOnSpawn
    sound:
      path: /Audio/Adventure/Hungry_Swarm/insect_speech.ogg
      params:
        volume: -8
  - type: IntrinsicRadioReceiver
    channels:
      - HungerSwarm
  - type: IntrinsicRadioTransmitter
    channels:
      - HungerSwarm
  - type: ActiveRadio
    channels:
      - HungerSwarm
  - type: Puller
    needsHands: false
  - type: MeleeWeapon
    altDisarm: false
    angle: 0
    damage:
      types:
        Piercing: 5
        Structural: 30
    soundHit:
     path: /Audio/Adventure/Hungry_Swarm/insect_attack.ogg
    animation: WeaponArcClaw
  - type: Hands
  - type: ComplexInteraction
  - type: Tag
    tags:
    - FootstepSound
    - HungerSwarm
  - type: Hunger 
    thresholds:
      Overfed: 35
      Okay: 25
      Peckish: 15
      Starving: 10
      Dead: 0
    baseDecayRate: 0.210
  - type: Bloodstream
    bloodReagent: InsectBlood
  - type: Devourer
    devourAction: ActionDevourHungerSwarm
    soundDevour: /Audio/Adventure/Hungry_Swarm/insect_eat.ogg
    soundStructureDevour: /Audio/Adventure/Hungry_Swarm/insect_eat.ogg
    foodPreference: All
    shouldStoreDevoured: true
    chemical: Protein
    healRate: 20
    devourTime: 5
    whitelist:
      components:
      - Item
  - type: TypingIndicator
    proto: default
  - type: StatusEffects
    allowed:
    - Stun
    - SlowedDown
    - Stutter
    - Electrocution
    - ForcedSleep
    - TemporaryBlindness
    - Pacified
    - RadiationProtection
    - Drowsiness
    - Adrenaline
  - type: FloatingVisuals
  - type: PassiveDamage
    allowedStates:
    - Alive
    damageCap: 1000
    damage:
      groups:
        Brute: -1.50
        Burn: -1.50
        Airloss: -1.50
        Toxin: -1.50
        Genetic: -1.50
  - type: Body
    prototype: HungerSwarm
  - type: GuideHelp
    guides:
    - HungerSwarm

#Тэг
- type: Tag
  id: HungerSwarm

- type: Tag
  id: HungerSwarmGuardian

#Радио 
- type: radioChannel
  id: HungerSwarm
  name: Коллективный разум 
  keycode: 'у'
  frequency: 426
  color: "#d2af52"
  longRange: true

#Броня 
- type: damageModifierSet
  id: HungerSwarm
  coefficients:
    Blunt: 0.95
    Slash: 0.85
    Piercing: 0.70
    Heat: 1.5

# Доступ
- type: accessLevel
  id: HungerSwarmAccess
  name: Возможность использовать постройки.

# Речь
- type: speechSounds
  id: HungerSwarmSpeech
  saySound:
    path: /Audio/Adventure/Hungry_Swarm/insect_speech.ogg
  askSound:
    path: /Audio/Adventure/Hungry_Swarm/insect_speech.ogg
  exclaimSound:
    path: /Audio/Adventure/Hungry_Swarm/insect_speech.ogg

#сердце
- type: entity
  id: OrganHeartReaper
  parent: BaseAnimalOrgan
  name: сердце жнеца
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    state: heart-on
  - type: Organ
  - type: Metabolizer
    maxReagents: 2
    metabolizerTypes: [ HungerSwarm ]
    groups:
    - id: Medicine
    - id: Poison
    - id: Narcotic
  - type: Item
    size: Small
    heldPrefix: heart

- type: metabolizerType
  id: HungerSwarm
  name: Рой

- type: body
  id: HungerSwarm
  name: "animal"
  root: torso
  slots:
    torso:
      part: TorsoAnimal
      connections:
      - legs
      organs:
        lungs: OrganAnimalLungs
        stomach: OrganAnimalStomach
        liver: OrganAnimalLiver
        heart: OrganHeartReaper
        kidneys: OrganAnimalKidneys
    legs:
      part: LegsAnimal
      connections:
      - feet
    feet:
      part: FeetAnimal

#Яд жнеца
- type: reagent
  id: ReaperPoison
  name: Яд жнеца
  group: Toxins
  desc: Используется жнецами-стражами для защиты улья.
  flavor: bitter
  color: "#e6a10f"
  physicalDesc: мерзкое
  metabolisms:
    Poison:
      effects:
      - !type:MovespeedModifier
        walkSpeedModifier: 0.90
        sprintSpeedModifier: 0.90
        conditions:
        - !type:OrganType
          type: HungerSwarm
          shouldHave: false
      - !type:GenericStatusEffect
        key: SeeingRainbows
        component: SeeingRainbows
        type: Add
        time: 5
        refresh: false
        conditions:
        - !type:OrganType
          type: HungerSwarm
          shouldHave: false

#Жнец-база
- type: entity
  abstract: true
  parent: [ BaseMobInsectSwarm, FlyingMobBase ]
  id: BaseMobInsectReaper
  components:
  - type: MobThresholds
    thresholds:
      0: Alive
      100: Dead
  - type: SlowOnDamage
    speedModifierThresholds:
      70: 0.7
  - type: GhostTakeoverAvailable
  - type: Butcherable
    spawned:
      - id: FoodMeat
        amount: 1
  - type: FootstepModifier
    footstepSoundCollection:
      collection: ReaperFly
      params: 
        volume: -10
  - type: Spider
    webPrototype: HungerSwarmWeb
    webAction: ActionHungerSwarmWeb
  - type: ActionGun
    action: ActionReaperSting
    gunProto: ReaperGun

- type: entity
  parent: BaseSubdermalImplant
  id: HungerSwarmImplant
  name: Рой
  description: Чувство коллективного разума, если дрон умрет.
  categories: [ HideSpawnMenu ]
  components:
    - type: SubdermalImplant
      permanent: true
      whitelist:
        components:
        - MobState
    - type: TriggerOnMobstateChange
      mobState:
      - Dead
    - type: Rattle
      radioChannel: HungerSwarm