#Слизь улья
- type: entity
  id: HungerSwarmWeb
  suffix: BORK (HungerSwarm)
  name: слизь улья жнецов
  description: Слизь, вырабатываемая жнецами для постройки улья.
  placement:
    mode: SnapgridCenter
    snap:
      - Wall
  components:
    - type: DamageContacts
      damage:
        groups:
          Brute: -0.5
          Burn: -0.5
          Airloss: -0.5
          Toxin: -0.5
          Genetic: -0.5
      ignoreWhitelist:
        tags:
        - CanPilot
        - CannotSuicide
        - VimPilot
    - type: MeleeSound
      soundGroups:
        Brute:
          path:
            "/Audio/Weapons/slash.ogg"
    - type: Sprite
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      layers:
        - state: tile
          map: ["spiderWebLayer"]
      drawdepth: LowFloors
    - type: Appearance
    - type: Clickable
    - type: Transform
      anchored: true
    - type: Physics
    - type: Fixtures
      fixtures:
        fix1:
          hard: false
          density: 7
          shape:
            !type:PhysShapeAabb
            bounds: "-0.5,-0.5,0.5,0.5"
          layer:
          - MidImpassable
    - type: Damageable
      damageModifierSet: HungerSwarm
    - type: Destructible
      thresholds:
      - trigger:
          !type:DamageTrigger
          damage: 30
        behaviors:
        - !type:DoActsBehavior
          acts: [ "Destruction" ]
    - type: Temperature
      heatDamage:
        types:
          Heat: 10
      coldDamage: {}
      ColdDamageThreshold: 0
    - type: Flammable
      fireSpread: true
      cold:
        types: {}
      damage:
        types:
          Heat: 10
    - type: Reactive
      groups:
        Flammable: [Touch]
        Extinguish: [Touch]
    - type: SpeedModifierContacts
      walkSpeedModifier: 0.7
      sprintSpeedModifier: 0.7
      ignoreWhitelist:
        tags:
        - HungerSwarm
    - type: EmitSoundOnSpawn
      sound:
        path: /Audio/Adventure/Hungry_Swarm/insect_spawn.ogg
        params: 
          volume: -5
    - type: GuideHelp
      guides:
      - HungerSwarm

#Слизь улья биоэлюмистентная
- type: entity
  id: HungerSwarmWebLight
  suffix: BORK (HungerSwarm)
  parent: HungerSwarmWeb
  name: биоэлюмистентная слизь улья жнецов
  description: Слизь, вырабатываемая жнецами для постройки улья.
  components:
    - type: Sprite
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      layers:
        - state: light
          map: ["spiderWebLayer"]
      drawdepth: FloorTiles
    - type: Fixtures
      fixtures:
        fix1:
          hard: false
          density: 7
          shape:
            !type:PhysShapeAabb
            bounds: "-0.5,-0.5,0.5,0.5"
          layer:
          - SlipLayer
    - type: PointLight
      radius: 3
      energy: 2
      color: "#d2af52"
    - type: RandomSprite
      available:
      - 0:
          light: ""
      - 0:
          light2: ""
      - 0:
          light3: ""

#Слизь улья клейкая
- type: entity
  id: HungerSwarmWebSticky
  suffix: BORK (HungerSwarm)
  parent: HungerSwarmWeb
  name: клейкая слизь улья жнецов
  description: Слизь, вырабатываемая жнецами для ловли добычи.
  components:
    - type: Sprite
      sprite: Adventure/Roles/Hungry_Swarm/other.rsi
      layers:
        - state: web
          map: ["spiderWebLayer"]
      drawdepth: Overdoors
    - type: RandomSprite
      available:
      - 0:
          web: ""
      - 0:
          web2: ""
      - 0:
          web3: ""
    - type: SpeedModifierContacts
      walkSpeedModifier: 0.2
      sprintSpeedModifier: 0.2
      ignoreWhitelist:
        tags:
        - HungerSwarm

#Стена улья
- type: entity
  parent: BaseWall
  id: HungerSwarmWall
  suffix: BORK (HungerSwarm)
  name: стена улья жнецов
  description: Довольно крепкое сооружение жнецов из слизи.
  components:
  - type: Damageable
    damageModifierSet: HungerSwarm
  - type: Sprite
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    state: wall
  - type: Icon
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    state: wall
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 400
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:PlaySoundBehavior
        sound:
          collection: WoodDestroy
  - type: GuideHelp
    guides:
    - HungerSwarm

- type: entity
  categories: [ HideSpawnMenu ]
  parent: WallSpawnAsteroid
  id: HungerSwarmWallSpawn
  components:
  - type: Sprite
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    state: wall_spawn
  - type: SpawnOnDespawn
    prototype: HungerSwarmWall
  - type: TimedDespawn
    lifetime: 1
  - type: EmitSoundOnSpawn
    sound:
      path: /Audio/Adventure/Hungry_Swarm/insect_spawn.ogg

#Укреплённая стена улья
- type: entity
  parent: BaseWall
  id: HungerSwarmWallReinforce
  suffix: BORK (HungerSwarm)
  name: укреплённая стена улья жнецов
  description: Довольно крепкое сооружение жнецов из слизи.
  components:
  - type: Damageable
    damageModifierSet: HungerSwarm
  - type: Sprite
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    state: reinforce_wall
  - type: Icon
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    state: reinforce_wall
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1000
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:PlaySoundBehavior
        sound:
          collection: WoodDestroy

- type: entity
  categories: [ HideSpawnMenu ]
  parent: WallSpawnAsteroid
  id: HungerSwarmWallReinforceSpawn
  components:
  - type: Sprite
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    state: wall_spawn
  - type: SpawnOnDespawn
    prototype: HungerSwarmWallReinforce
  - type: TimedDespawn
    lifetime: 1
  - type: EmitSoundOnSpawn
    sound:
      path: /Audio/Adventure/Hungry_Swarm/insect_spawn.ogg

#Дверь улья
- type: entity
  id: HungerSwarmDoor
  parent: BaseStructure
  name: проход улья жнецов
  suffix: BORK (HungerSwarm)
  description: Никто не знает, что вас ждёт за этим проходом.
  placement:
    mode: SnapgridCenter
  components:
  - type: InteractionOutline
  - type: Sprite
    sprite: Adventure/Roles/Hungry_Swarm/door.rsi
    layers:
    - state: closed
      map: ["enum.DoorVisualLayers.Base"]
    - state: closed_unlit
      map: ["enum.DoorVisualLayers.BaseUnlit"]
    - state: welded
      map: ["enum.WeldableLayers.BaseWelded"]
    - state: bolted_unlit
      map: ["enum.DoorVisualLayers.BaseBolted"]
    - state: emergency_unlit
      map: ["enum.DoorVisualLayers.BaseEmergencyAccess"]
    - state: panel_open
      map: ["enum.WiresVisualLayers.MaintenancePanel"]
  - type: AnimationPlayer
  - type: Physics
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,0.49"
        density: 100
        mask:
        - FullTileMask
        layer:
        - WallLayer
  - type: DoorBolt
  - type: Door
    closeTimeTwo: 0.4
    openTimeTwo: 0.4
    crushDamage:
      types:
        Blunt: 50
    openSound:
      path: /Audio/Adventure/Hungry_Swarm/insect_door_opening.ogg
    closeSound:
      path: /Audio/Adventure/Hungry_Swarm/insect_door_closing.ogg
    denySound:
      path: /Audio/Adventure/Hungry_Swarm/insect_spawn.ogg
  - type: Airlock
    openUnlitVisible: true
  - type: NavMapDoor
  - type: AccessReader
    access: [["HungerSwarmAccess"]]
  - type: Appearance
  - type: WiresVisuals
  - type: ApcPowerReceiver
    powerLoad: 0
  - type: ExtensionCableReceiver
  - type: Electrified
    enabled: false
    usesApcPower: true
  - type: Airtight
  - type: Occluder
  - type: Damageable
    damageContainer: StructuralInorganic
    damageModifierSet: HungerSwarm
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 400
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
      - !type:PlaySoundBehavior
        sound:
          collection: WoodDestroy
  - type: Tag
    tags:
      - Airlock
      - EmagImmune
  - type: GuideHelp
    guides:
    - HungerSwarm

- type: entity
  categories: [ HideSpawnMenu ]
  parent: WallSpawnAsteroid
  id: HungerSwarmDoorSpawn
  components:
  - type: Sprite
    sprite: Adventure/Roles/Hungry_Swarm/other.rsi
    state: door_spawn
  - type: SpawnOnDespawn
    prototype: HungerSwarmDoor
  - type: TimedDespawn
    lifetime: 1
  - type: EmitSoundOnSpawn
    sound:
      path: /Audio/Adventure/Hungry_Swarm/insect_spawn.ogg